//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_produto
    {
        public int id_produto { get; set; }
        public string nm_produto { get; set; }
        public string ds_produto { get; set; }
        public decimal vl_produto { get; set; }
    }
}
